language: cpp

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

addons:
  apt:
    packages:
      - g++-multilib

git:
  submodules: false

before_install:
  - git submodule update --init --recursive . ":(exclude)lib/boost"
  - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz
  - tar xzf boost_1_65_1.tar.gz

install:
  - cd boost_1_65_1
  - ./bootstrap.sh
  - ./b2 --with-system address-model=32
  - cd ..

before_script:
  - mkdir build && cd build
  - export TRAVIS_COMMIT_SHORT="$(git rev-parse --short ${TRAVIS_COMMIT})"
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCPACK_OUTPUT_FILE_POSTFIX=${BUILD_TYPE} -DBOOST_ROOT=boost_1_65_1 -DEIGEN3_INCLUDE_DIR=lib/eigen -DCOMMIT_ID=${TRAVIS_COMMIT_SHORT}

script:
  - make streamer_unity
  - make package
  - cd ..
