version: '{build}'
image: Visual Studio 2015

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive . ":(exclude)lib/boost"

before_build:
  - mkdir build && cd build
  - git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%/short.txt
  - set /p APPVEYOR_REPO_COMMIT_SHORT=<%TMP%/short.txt
  - cmake .. -G "Visual Studio 14 2015" -DCPACK_OUTPUT_FILE_POSTFIX=%CONFIGURATION% -DBOOST_ROOT="C:\Libraries\boost_1_65_1" -DEIGEN3_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\lib\eigen" -DCOMMIT_ID="%APPVEYOR_REPO_COMMIT_SHORT%"

build_script:
  - cmake --build . --config %CONFIGURATION% --target streamer_unity
  - cmake --build . --config %CONFIGURATION% --target package
  - cd ..

artifacts:
  - path: build\package
